Align with recent changes to the lib template.

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -6,13 +6,127 @@ on:
   push:
   workflow_dispatch:
 
+env:
+  APP_SCHEME: "App"
+  PROJECT: "App.xcodeproj"
+  WATCH_SCHEME: "WatchApp"
+
 jobs:
-  app:
-    uses: Brent-Tunnicliff/workflow-common-apple/.github/workflows/common.yml@v1
+  test:
+    runs-on: macos-15
     strategy:
+      # Don't fail the other matrix values if one fails.
+      fail-fast: false
       matrix:
-        platform: ["iOS", "macOS", "tvOS", "visionOS"]
-    with:
-      platform: "${{ matrix.platform }}"
-      scheme: "App"
-      skip_tests: false
+        target: [
+          { platform: "iOS", simulator_version: "18" },
+          { platform: "tvOS", simulator_version: "18" },
+          { platform: "watchOS", simulator_version: "11" },
+          { platform: "visionOS", simulator_version: "2" },
+
+          # macOS runs on the host and doesn't need a simulator.
+          { platform: "macOS", simulator_version: "" }
+        ]
+    steps:
+      # ---------------------------
+      # Setup
+      # ---------------------------
+
+      - name: Setup pipeline
+        id: setup
+        uses: Brent-Tunnicliff/action-setup-apple@v1
+        with:
+          platform: "${{ matrix.target.platform }}"
+          simulator_version: "${{ matrix.target.simulator_version }}"
+          xcode_path: "/Applications/Xcode_16.4.app"
+
+      - name: Configure scheme
+        id: scheme_config
+        env:
+          PLATFORM: ${{ matrix.target.platform }}
+        run: |
+          if [[ "$PLATFORM" == "watchOS" ]]; then
+            SCHEME="$WATCH_SCHEME"
+          else
+            SCHEME="$APP_SCHEME"
+          fi
+
+          if [[ $SCHEME == "" ]]; then
+            echo "SCHEME missing"
+            exit 1
+          fi
+
+          echo $SCHEME
+          echo "scheme=$SCHEME" >> "$GITHUB_OUTPUT"
+
+      # ---------------------------
+      # Build and test app
+      # ---------------------------
+
+      - name: Build debug
+        env:
+          DESTINATION: ${{ steps.setup.outputs.destination }}
+          SCHEME: ${{ steps.scheme_config.scheme }}
+        run: xcodebuild build
+          -project "$PROJECT"
+          -scheme "$SCHEME"
+          -destination "$DESTINATION"
+          -configuration "Debug"
+          -skipPackagePluginValidation
+          CODE_SIGN_IDENTITY=""
+          CODE_SIGNING_REQUIRED=NO
+
+      - name: Build tests
+        env:
+          DESTINATION: ${{ steps.setup.outputs.destination }}
+          SCHEME: ${{ steps.scheme_config.scheme }}
+        run: xcodebuild build-for-testing
+          -project "$PROJECT"
+          -scheme "$SCHEME"
+          -destination "$DESTINATION"
+          -skipPackagePluginValidation
+          CODE_SIGN_IDENTITY=""
+          CODE_SIGNING_REQUIRED=NO
+
+      - name: Run tests
+        env:
+          DESTINATION: ${{ steps.setup.outputs.destination }}
+          RESULTS_BUNDLE_PATH: ${{ steps.setup.outputs.test_results_path }}
+          SCHEME: ${{ steps.scheme_config.scheme }}
+        run: xcodebuild test-without-building
+          -project "$PROJECT"
+          -scheme "$SCHEME"
+          -destination "$DESTINATION"
+          -resultBundlePath "$RESULTS_BUNDLE_PATH"
+          CODE_SIGN_IDENTITY=""
+          CODE_SIGNING_REQUIRED=NO
+
+      - name: Upload test results
+        if: success() || failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: "${{ steps.setup.outputs.test_results_file_name }}"
+          path: "${{ steps.setup.outputs.test_results_path }}"
+          if-no-files-found: error
+
+      # Lets make sure it also builds in release configuration in case there are conditionals.
+      - name: Build release
+        env:
+          DESTINATION: ${{ steps.setup.outputs.destination }}
+          SCHEME: ${{ steps.scheme_config.scheme }}
+        run: xcodebuild build
+          -project "$PROJECT"
+          -scheme "$SCHEME"
+          -destination "$DESTINATION"
+          -configuration "Release"
+          -skipPackagePluginValidation
+          CODE_SIGN_IDENTITY=""
+          CODE_SIGNING_REQUIRED=NO
+
+      # ---------------------------
+      # Final checks
+      # ---------------------------
+
+      # Make sure there are no local changes as any auto generated changes must be checked into git.
+      - name: Check git status
+        uses: Brent-Tunnicliff/action-git-status@v1
